#!/usr/bin/env node
// github#127 -- design/0018

import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const CHECK = process.argv.includes("--check");
const GALLERY = "docs/features.md";
const read = (p) => readFileSync(join(ROOT, p), "utf8");

const START = "<!-- gallery-nav:start (generated by scripts/gallery-nav.mjs -- do not edit by hand) -->";
const END = "<!-- gallery-nav:end -->";

/* ---------------------------------------------------------- the gallery's own anchor map -- */

// design/0018
function anchorsByTitle(galleryText) {
  const map = new Map();
  for (const m of galleryText.matchAll(/\[([^\]]+)\]\(#([a-z0-9-]+)\)/g)) map.set(m[1], m[2]);
  return map;
}

/* -------------------------------------------------------------------- per-feature metadata -- */

// design/0018
const TITLE = /^#\s+(.+?)\s*$/m;
const INTRODUCED = /\*\*Introduced in\*\*\s*\|\s*`([^`]+)`/;
const VERSION = /^(v)?(\d+(?:\.\d+){1,2})/;

function readFeature(file) {
  const text = read(`docs/features/${file}`);
  const title = TITLE.exec(text)?.[1];
  const cell = INTRODUCED.exec(text)?.[1];
  const v = cell && VERSION.exec(cell.trim());
  if (!title || !v) return null;
  const parts = v[2].split(".").map(Number);
  while (parts.length < 3) parts.push(0);
  const display = `${v[1] || ""}${v[2]}`;
  return { title, display, tuple: parts };
}

function compareTuples(a, b) {
  for (let i = 0; i < 3; i++) if (a[i] !== b[i]) return a[i] - b[i];
  return 0;
}

/* ------------------------------------------------------------------------------- generate -- */

// design/0018
function buildNavLine(galleryText) {
  const anchors = anchorsByTitle(galleryText);
  const files = readdirSync(join(ROOT, "docs/features")).filter(
    (f) => f.endsWith(".md") && f !== "_template.md",
  );
  const features = files.map(readFeature).filter(Boolean);

  let top = null;
  for (const f of features) {
    if (!anchors.has(f.title)) continue;
    if (!top || compareTuples(f.tuple, top) > 0) top = f.tuple;
  }
  if (!top) return null;

  const entries = features.filter((f) => anchors.has(f.title) && compareTuples(f.tuple, top) === 0);
  const version = entries[0].display;
  const links = entries.map((f) => `[${f.title}](#${anchors.get(f.title)})`).join(" · ");
  return `> **New in ${version}** — ${links}`;
}

/* ----------------------------------------------------------------------------------- run -- */

const galleryText = read(GALLERY);
const line = buildNavLine(galleryText);
if (!line) {
  console.error("gallery-nav: no feature has both a resolvable version and a gallery section -- nothing to write");
  process.exit(CHECK ? 1 : 0);
}
const block = `${START}\n${line}\n${END}`;

const escaped = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
const markerRe = new RegExp(`${escaped(START)}\\n.*\\n${escaped(END)}`);
const updated = markerRe.test(galleryText)
  ? galleryText.replace(markerRe, block)
  : galleryText.replace(/\n(?=\| \| \|\n\|---\|---\|)/, `\n${block}\n\n`);

if (CHECK) {
  if (updated !== galleryText) {
    console.error(`gallery-nav: ${GALLERY} is stale -- run: node scripts/gallery-nav.mjs`);
    process.exit(1);
  }
  console.log(`gallery-nav: ${GALLERY} is current (${line})`);
} else {
  if (updated !== galleryText) {
    writeFileSync(join(ROOT, GALLERY), updated, "utf8");
    console.log(`gallery-nav: wrote ${GALLERY} -- ${line}`);
  } else {
    console.log(`gallery-nav: ${GALLERY} already current -- ${line}`);
  }
}
